package com.bdt.framework.mapper;

import com.bdt.framework.entity.Admin;
import com.bdt.framework.orm.mybatis.utils.CustomMapper;
import com.github.pagehelper.Page;

import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Oct 04 18:49:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Oct 04 18:49:06 CST 2016
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Oct 04 18:49:06 CST 2016
     */
    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Oct 04 18:49:06 CST 2016
     */
    Page<Admin> selectAll();

    /**
     * 根据用户名称查询用户信息
     * @param account
     * @return
     */
    List<Admin> selectByAccount(String account);


    /**
     * 根据用户名称查询用户信息
     * @param account
     * @return
     */
    Admin selectByAccounts(String account);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Oct 04 18:49:06 CST 2016
     */
    int updateByPrimaryKey(Admin record);
}