package com.bdt.framework.mapper;

import com.bdt.framework.entity.SysResource;
import java.util.List;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    SysResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    List<SysResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int updateByPrimaryKey(SysResource record);
}