package com.bdt.framework.mapper;

import com.bdt.framework.entity.SysRoleResource;
import java.util.List;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    List<SysRoleResource> selectAll();
}