package com.bdt.framework.mapper;

import com.bdt.framework.entity.SysUserRole;
import java.util.List;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    List<SysUserRole> selectAll();
}