package com.bdt.framework.mapper;

import com.bdt.framework.entity.WebTaskItem;
import java.util.List;

public interface WebTaskItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_item
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_item
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int insert(WebTaskItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_item
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    WebTaskItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_item
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    List<WebTaskItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_item
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int updateByPrimaryKey(WebTaskItem record);

    List<WebTaskItem> selectByGroupDomain();

    List<WebTaskItem> selectByAdminId(Integer adminId);

}