package com.bdt.framework.mapper;

import com.bdt.framework.entity.WebTask;

import java.util.List;

public interface WebTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int insert(WebTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    WebTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    List<WebTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    int updateByPrimaryKey(WebTask record);
}