package com.bdt.framework.entity;

public class SysRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.resource_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.role_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.resource_id
     *
     * @return the value of sys_role_resource.resource_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.resource_id
     *
     * @param resourceId the value for sys_role_resource.resource_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.role_id
     *
     * @return the value of sys_role_resource.role_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.role_id
     *
     * @param roleId the value for sys_role_resource.role_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}