package com.bdt.framework.entity;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.url
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.permission
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.is_enable
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_ids
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.order_by
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.icon
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.permission
     *
     * @return the value of sys_resource.permission
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.permission
     *
     * @param permission the value for sys_resource.permission
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.is_enable
     *
     * @return the value of sys_resource.is_enable
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.is_enable
     *
     * @param isEnable the value for sys_resource.is_enable
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_ids
     *
     * @return the value of sys_resource.parent_ids
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_ids
     *
     * @param parentIds the value for sys_resource.parent_ids
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.order_by
     *
     * @return the value of sys_resource.order_by
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.order_by
     *
     * @param orderBy the value for sys_resource.order_by
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.icon
     *
     * @return the value of sys_resource.icon
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.icon
     *
     * @param icon the value for sys_resource.icon
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}