package com.bdt.framework.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.validatecode
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String validatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.registertime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Date registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.tokenexptime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Long tokenexptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.validatecode
     *
     * @return the value of sys_user.validatecode
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getValidatecode() {
        return validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.validatecode
     *
     * @param validatecode the value for sys_user.validatecode
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setValidatecode(String validatecode) {
        this.validatecode = validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.registertime
     *
     * @return the value of sys_user.registertime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.registertime
     *
     * @param registertime the value for sys_user.registertime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.tokenexptime
     *
     * @return the value of sys_user.tokenexptime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Long getTokenexptime() {
        return tokenexptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.tokenexptime
     *
     * @param tokenexptime the value for sys_user.tokenexptime
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setTokenexptime(Long tokenexptime) {
        this.tokenexptime = tokenexptime;
    }
}