package com.bdt.framework.entity;

import java.util.Date;

public class WebTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.keyword
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.disabled
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.page_title
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String pageTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.times
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.task_date
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Date taskDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.disable_js
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean disableJs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.id
     *
     * @return the value of web_task.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.id
     *
     * @param id the value for web_task.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.keyword
     *
     * @return the value of web_task.keyword
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.keyword
     *
     * @param keyword the value for web_task.keyword
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.admin_id
     *
     * @return the value of web_task.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.admin_id
     *
     * @param adminId the value for web_task.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.disabled
     *
     * @return the value of web_task.disabled
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.disabled
     *
     * @param disabled the value for web_task.disabled
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.page_title
     *
     * @return the value of web_task.page_title
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.page_title
     *
     * @param pageTitle the value for web_task.page_title
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.times
     *
     * @return the value of web_task.times
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.times
     *
     * @param times the value for web_task.times
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.domain
     *
     * @return the value of web_task.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.domain
     *
     * @param domain the value for web_task.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.create_time
     *
     * @return the value of web_task.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.create_time
     *
     * @param createTime the value for web_task.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.task_date
     *
     * @return the value of web_task.task_date
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Date getTaskDate() {
        return taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.task_date
     *
     * @param taskDate the value for web_task.task_date
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setTaskDate(Date taskDate) {
        this.taskDate = taskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.disable_js
     *
     * @return the value of web_task.disable_js
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getDisableJs() {
        return disableJs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.disable_js
     *
     * @param disableJs the value for web_task.disable_js
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setDisableJs(Boolean disableJs) {
        this.disableJs = disableJs;
    }
}