package com.bdt.framework.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WebTaskItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.task_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.finished
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean finished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.hour
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.running
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private Boolean running;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    private String domain;



    /**
     * 总点击数的价格
     */
    private String  expense;
    /**
     * 点击总数
     */
    private Integer num;
    /**
     * 用户余额
     */
    private BigDecimal balance;
    /**
     * 用户名
     */
    private String account;

    public String getExpense() {
        return expense;
    }

    public void setExpense(String expense) {
        this.expense = expense;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.id
     *
     * @return the value of web_task_item.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.id
     *
     * @param id the value for web_task_item.id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.task_id
     *
     * @return the value of web_task_item.task_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.task_id
     *
     * @param taskId the value for web_task_item.task_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.admin_id
     *
     * @return the value of web_task_item.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.admin_id
     *
     * @param adminId the value for web_task_item.admin_id
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.finished
     *
     * @return the value of web_task_item.finished
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.finished
     *
     * @param finished the value for web_task_item.finished
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.hour
     *
     * @return the value of web_task_item.hour
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.hour
     *
     * @param hour the value for web_task_item.hour
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.create_time
     *
     * @return the value of web_task_item.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.create_time
     *
     * @param createTime the value for web_task_item.create_time
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.running
     *
     * @return the value of web_task_item.running
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public Boolean getRunning() {
        return running;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.running
     *
     * @param running the value for web_task_item.running
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setRunning(Boolean running) {
        this.running = running;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.domain
     *
     * @return the value of web_task_item.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.domain
     *
     * @param domain the value for web_task_item.domain
     *
     * @mbggenerated Sat Mar 25 19:52:14 CST 2017
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }
}